print("hello")
name = input("what is your name ? ")
print(" hello " +name)
born = int(input(" which year did you born in ? "))
year = int(input("which year you are now ? "))
age = int(year) - int(born)
print("your current age is  " + str(age))